name: test-coverage
on:
  push:
    branches:
      - main
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/*
      - test/*
      - '*.json'
      - package-lock.lock
  pull_request:
    paths:
      - '!*.MD'
jobs:
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: make install
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
